# Generated by Django 3.1.5 on 2021-01-10 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
