# Generated by Django 3.1.5 on 2021-01-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alertfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertfeed',
            name='feed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_alertfeed', to='feed.feed'),
        ),
    ]
